version: "2.1"
services:
  elasticsearch: #service name
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      # - 9300:9300
    environment:
      - discovery.type=single-node #for single node
      - node.name=es-intro-node
      - cluster.name=es-intro-cluster
    networks:
      - es

  kibana:
    image: kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      #http://{the_elasticsearch_service_name}:9200 (and not localhost !)
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    networks:
      - es
    depends_on:
      - elasticsearch

networks:
  es:
    driver: bridge
